//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace transtrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statement
    {
        public int Id { get; set; }
        public string AccountType { get; set; }
        public long AccountNum { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public double Amount { get; set; }
        public string Store { get; set; }
        public string Location { get; set; }
        public string Name { get; set; }
    }
}
